language: elixir
sudo: false

cache:
  directories:
    - deps
    - _build/test

elixir: 1.8.0
otp_release: 21.1

matrix:
  include:
    - elixir: 1.7.0
      otp_releae: 20.2
    - elixir: 1.6.0
      otp_release: 20.1
    - elixir: 1.5.2
      otp_release: 18.1  

script: mix coveralls.travis